version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build from Dockerfile
          command: docker build -t pingcheng/pct-base .

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: Push to Docker Hub
          command: docker push pingcheng/pct-base

      - run:
          name: Trigger PingChengTech build
          command: |
            curl -u ${CIRCLE_API_USER_TOKEN}: \
            -d build_parameters[CIRCLE_JOB]=test \
            https://circleci.com/api/v1.1/project/github/pingcheng/pingchengtech/tree/master


workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master