version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build from Dockerfile
          command: docker build -t pingcheng/pct-base .

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run:
          name: Push to Docker Hub
          command: docker push pingcheng/pct-base


workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master